import {
  createReadableStreamFromReadable,
  readableStreamToString,
} from "@react-router/node";
import { createRequestHandler as createReactRouterRequestHandler } from "react-router";

const serializeLogSegment = (segment) => {
  try {
    return JSON.stringify(segment);
  } catch {
    return String(segment);
  }
};

const logger = {
  error: (scope, message, meta = []) => console.error(scope, message, meta),
};

/**
 * Returns a request handler for Hapi that serves the response using React Router.
 * Original from: https://github.com/mcansh/remix-node-http-server/blob/main/packages/remix-raw-http/src/server.ts
 *
 * A function that returns the value to use as `context` in route `loader` and
 * `action` functions.
 *
 * You can think of this as an escape hatch that allows you to pass
 * environment/platform-specific values through to your loader/action, such as
 * values that are generated by middleware like `req.session`.
 *
 * @callback GetLoadContextFunction
 * @param {import("@hapi/hapi").Request} req
 * @param {import("@hapi/hapi").ResponseToolkit} res
 * @returns {Promise<Record<string, unknown>>}
 *
 * @param {{
 *  build: import("react-router").ServerBuild,
 *  getLoadContext?: GetLoadContextFunction,
 *  mode?: string
 * }} params
 * @returns {(hapiReq: import("@hapi/hapi").Request, h: import("@hapi/hapi").ResponseToolkit) => Promise<unknown>}
 */
export const createRequestHandler = ({ build, getLoadContext, mode = process.env.NODE_ENV }) => {
  const handleRequest = createReactRouterRequestHandler(build, mode);

  return async (hapiReq, h) => {
    try {
      const request = createReactRouterRequest(hapiReq);
      const loadContext = await getLoadContext?.(hapiReq, h);
      const response = await handleRequest(request, loadContext);

      return await sendReactRouterResponse(h, response);
    } catch (error) {
      logger.error("createRequestHandler", "Failure adapting request to React Router", [
        serializeLogSegment({
          method: hapiReq?.method?.toUpperCase?.() ?? hapiReq?.method,
          path: hapiReq?.path,
        }),
        serializeLogSegment(error),
      ]);

      throw error;
    }
  };
};

const createReactRouterHeaders = (requestHeaders) => {
  const headers = new Headers();

  for (const [key, values] of Object.entries(requestHeaders)) {
    if (!values) {
      continue;
    }

    if (Array.isArray(values)) {
      for (const value of values) {
        headers.append(key, value);
      }
      continue;
    }

    headers.set(key, values);
  }

  return headers;
};

const getUrl = (rawReq) => new URL(`http://${rawReq.headers.host}${rawReq.url}`);

const isContentTypeFormUrlEncoded = (rawReq) => {
  const contentType = rawReq.headers["content-type"] || "";

  return contentType.includes("application/x-www-form-urlencoded");
};

const createReactRouterRequest = (hapiReq) => {
  const rawReq = hapiReq.raw.req;
  const rawRes = hapiReq.raw.res;
  const url = getUrl(rawReq);

  const controller = new AbortController();
  rawRes.on("close", () => controller.abort());

  const init = {
    method: rawReq.method,
    headers: createReactRouterHeaders(rawReq.headers),
    signal: controller.signal,
  };

  if (rawReq.method !== "GET" && rawReq.method !== "HEAD") {
    let body;

    if (isContentTypeFormUrlEncoded(rawReq)) {
      const params = new URLSearchParams(hapiReq.payload);
      body = params.toString();
    } else {
      body = createReadableStreamFromReadable(rawReq);
      init.duplex = "half";
    }

    init.body = body;
  }

  return new Request(url.href, init);
};

const sendReactRouterResponse = async (h, nodeResponse) => {
  const headers = {};
  nodeResponse.headers.forEach((value, key) => {
    headers[key] = value;
  });

  const hapiReq = h.request;
  const rawReq = hapiReq.raw.req;
  let body = "";

  if (nodeResponse.body) {
    if (isContentTypeFormUrlEncoded(rawReq)) {
      body = await nodeResponse.text();
    } else {
      body = await readableStreamToString(nodeResponse.body);
    }
  } else {
    h.request.raw.res.end();
  }

  const response = h.response(body).code(nodeResponse.status).message(nodeResponse.statusText);

  Object.entries(headers).forEach(([key, value]) => response.header(key, value));

  return response;
};
